# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "toon.y".
#

require 'racc/parser.rb'
module Toonrb
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     2,    14,    14,    14,    39,    31,    38,    42,    25,    18,
    19,    20,    21,    22,    23,    14,    23,    24,   -55,    24,
    22,   -55,    18,    19,    20,    21,    22,    23,    14,    23,
    24,    23,    24,    47,    24,    18,    19,    20,    21,    22,
    23,    14,    23,    24,    23,    24,    49,    24,    18,    19,
    20,    21,    22,    23,    14,    23,    24,    23,    24,    52,
    24,    18,    19,    20,    21,    22,    23,    18,    19,    24,
    18,    19,    20,    21,    22,    23,    18,    19,    24,    18,
    19,    20,    21,    22,    18,    19,    20,    21,    22,    18,
    19,    20,    21,    22,    18,    19,    18,    19,    18,    19,
    18,    19,    55,    60,    65,    49,    73,    74,    77,    60,
    82,    88,    49,    92,    74,    96,   100,    96 ]

racc_action_check = [
     1,     8,     1,    29,    12,     8,    12,    29,     2,     1,
     1,     1,     1,     1,     1,    31,     5,     1,     9,     5,
    13,     9,    31,    31,    31,    31,    31,    31,    42,    11,
    31,    34,    11,    33,    34,    42,    42,    42,    42,    42,
    42,    64,    45,    42,    58,    45,    35,    58,    64,    64,
    64,    64,    64,    64,    96,    69,    64,    85,    69,    37,
    85,    96,    96,    96,    96,    96,    96,     7,     7,    96,
    10,    10,    10,    10,    10,    10,    27,    27,    10,    49,
    49,    49,    49,    49,    52,    52,    52,    52,    52,    70,
    70,    70,    70,    70,    39,    39,    60,    60,    74,    74,
    80,    80,    40,    44,    47,    50,    53,    54,    56,    57,
    63,    68,    72,    73,    75,    83,    95,    97 ]

racc_action_pointer = [
   nil,     0,     8,   nil,   nil,     2,   nil,    58,    -1,     4,
    61,    15,     0,     7,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    67,   nil,     1,
   nil,    13,   nil,    18,    17,    38,   nil,    44,   nil,    85,
    94,   nil,    26,   nil,    88,    28,   nil,    97,   nil,    70,
    97,   nil,    75,   101,    99,   nil,   105,    94,    30,   nil,
    87,   nil,   nil,    94,    39,   nil,   nil,   nil,    95,    41,
    80,   nil,   104,   107,    89,   106,   nil,   nil,   nil,   nil,
    91,   nil,   nil,   108,   nil,    43,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   100,    52,   110,   nil,   nil,
   nil,   nil,   nil ]

racc_action_default = [
    -1,   -66,   -66,    -2,    -3,   -66,    -5,    -6,   -66,   -15,
   -66,   -66,   -66,   -66,   -32,   -56,   -57,   -58,   -59,   -60,
   -61,   -62,   -63,   -64,   -65,   103,    -4,    -6,    -8,   -66,
   -21,   -66,   -12,   -22,   -66,   -38,   -55,   -25,   -27,   -66,
   -29,    -7,   -66,   -18,   -10,   -66,   -13,   -66,   -23,   -66,
   -38,   -40,   -66,   -66,   -34,   -30,   -66,   -16,   -66,   -19,
   -66,   -14,   -11,   -66,   -66,   -45,   -37,   -39,   -66,   -66,
   -51,   -53,   -38,   -66,   -66,   -34,   -36,   -31,   -20,   -17,
    -6,   -15,   -24,   -42,   -46,   -66,   -48,   -49,   -26,   -50,
   -52,   -54,   -28,   -33,   -35,   -66,   -66,   -42,   -44,   -47,
    -9,   -41,   -43 ]

racc_goto_table = [
     5,     9,     6,    28,    76,    51,    26,    30,     4,    35,
    71,    33,    37,    83,     1,    32,    61,    98,     3,    80,
    67,    34,    63,    41,    68,    94,    53,    30,    90,    78,
    45,   102,    44,    40,    56,    48,    43,    64,    46,    54,
   nil,    58,    91,    57,   nil,   101,    62,   nil,    66,    59,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    79,
    81,   nil,   nil,    85,     9,   nil,   nil,   nil,   nil,   nil,
    89,   nil,   nil,   nil,    93,   nil,    95,   nil,   nil,   nil,
    30,   nil,   nil,   nil,   nil,   nil,    99,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    85,     9 ]

racc_goto_check = [
     4,    11,     5,     9,    24,    26,     5,    11,     3,     4,
    33,     5,     5,    28,     1,     3,     8,    30,     2,     6,
    26,    14,    15,     9,    17,    24,    19,    11,    33,     8,
     4,    30,     5,    21,    22,     5,     3,    27,     3,    11,
   nil,     4,    26,     5,   nil,    28,     5,   nil,     4,     3,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,
    11,   nil,   nil,     4,    11,   nil,   nil,   nil,   nil,   nil,
     5,   nil,   nil,   nil,    11,   nil,     9,   nil,   nil,   nil,
    11,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     4,    11 ]

racc_goto_pointer = [
   nil,    14,    17,     7,    -1,     1,   -41,   nil,   -28,    -4,
   nil,     0,   nil,   nil,    11,   -25,   nil,   -28,   nil,   -13,
   nil,    20,    -6,   nil,   -50,   nil,   -30,   -10,   -51,   nil,
   -66,   nil,   nil,   -42,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    87,    86,    72,    84,     7,    27,   nil,   nil,
     8,    36,    29,    10,   nil,   nil,    11,   nil,    12,   nil,
    13,    17,   nil,    75,   nil,    50,   nil,   nil,   nil,    97,
   nil,    69,    70,   nil,    15,    16 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 20, :_reduce_none,
  2, 20, :_reduce_none,
  2, 20, :_reduce_none,
  3, 20, :_reduce_4,
  2, 20, :_reduce_none,
  0, 28, :_reduce_6,
  2, 28, :_reduce_7,
  2, 21, :_reduce_8,
  4, 27, :_reduce_9,
  3, 25, :_reduce_10,
  4, 25, :_reduce_11,
  2, 25, :_reduce_none,
  3, 25, :_reduce_none,
  4, 25, :_reduce_none,
  1, 29, :_reduce_15,
  3, 26, :_reduce_16,
  4, 26, :_reduce_17,
  2, 26, :_reduce_none,
  3, 26, :_reduce_none,
  4, 26, :_reduce_none,
  1, 31, :_reduce_21,
  2, 22, :_reduce_22,
  3, 22, :_reduce_23,
  5, 22, :_reduce_24,
  2, 22, :_reduce_25,
  5, 22, :_reduce_26,
  2, 32, :_reduce_none,
  5, 35, :_reduce_none,
  0, 41, :_reduce_none,
  1, 41, :_reduce_none,
  4, 37, :_reduce_31,
  1, 39, :_reduce_32,
  2, 42, :_reduce_33,
  0, 43, :_reduce_34,
  2, 43, :_reduce_35,
  2, 38, :_reduce_36,
  2, 44, :_reduce_37,
  0, 45, :_reduce_38,
  2, 45, :_reduce_39,
  2, 33, :_reduce_40,
  2, 48, :_reduce_41,
  0, 49, :_reduce_42,
  2, 49, :_reduce_43,
  3, 34, :_reduce_none,
  1, 46, :_reduce_45,
  1, 47, :_reduce_46,
  2, 47, :_reduce_47,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  2, 51, :_reduce_50,
  1, 52, :_reduce_51,
  2, 52, :_reduce_52,
  1, 36, :_reduce_none,
  2, 50, :_reduce_54,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 30, :_reduce_59,
  1, 30, :_reduce_60,
  1, 53, :_reduce_61,
  1, 54, :_reduce_62,
  1, 40, :_reduce_63,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none ]

racc_reduce_n = 66

racc_shift_n = 103

racc_token_table = {
  false => 0,
  :error => 1,
  :L_BRACKET => 2,
  :R_BRACKET => 3,
  :L_BRACE => 4,
  :R_BRACE => 5,
  :COLON => 6,
  :HYPHEN => 7,
  :DELIMITER => 8,
  :QUOTED_STRING => 9,
  :UNQUOTED_STRING => 10,
  :BOOLEAN => 11,
  :NULL => 12,
  :NUMBER => 13,
  :NL => 14,
  :PUSH_INDENT => 15,
  :POP_INDENT => 16,
  :EOS => 17,
  "-temp-group" => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "L_BRACKET",
  "R_BRACKET",
  "L_BRACE",
  "R_BRACE",
  "COLON",
  "HYPHEN",
  "DELIMITER",
  "QUOTED_STRING",
  "UNQUOTED_STRING",
  "BOOLEAN",
  "NULL",
  "NUMBER",
  "NL",
  "PUSH_INDENT",
  "POP_INDENT",
  "EOS",
  "\"-temp-group\"",
  "$start",
  "root",
  "object",
  "array",
  "primitive",
  "eol",
  "object_head_item",
  "object_item",
  "object_nested",
  "\"-many@object_item\"",
  "object_head_key",
  "string",
  "object_key",
  "array_header",
  "inline_array_values",
  "list_array_items",
  "tebular_array_header",
  "tabular_rows",
  "array_header_common",
  "tabular_fields",
  "array_header_start",
  "number",
  "\"-option@DELIMITER\"",
  "\"-group@DELIMITER-string\"",
  "\"-many@-group@DELIMITER-string\"",
  "\"-group@DELIMITER-primitive\"",
  "\"-many@-group@DELIMITER-primitive\"",
  "list_array_items_start",
  "list_array_value",
  "\"-group@HYPHEN-list_array_value\"",
  "\"-many@-group@HYPHEN-list_array_value\"",
  "tabular_row",
  "\"-group@tabular_row-eol\"",
  "\"-many1@-group@tabular_row-eol\"",
  "boolean",
  "null" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_4(val, _values, result)
            handler.push_value(val[1])

    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'toon.y', 35)
  def _reduce_6(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 35)
  def _reduce_7(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 31)
  def _reduce_8(val, _values, result)
            handler.pop

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 35)
  def _reduce_9(val, _values, result)
            handler.pop

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 39)
  def _reduce_10(val, _values, result)
            position = scanner.current_position
        handler.push_empty_object(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 43)
  def _reduce_11(val, _values, result)
            handler.push_value(val[2])

    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'toon.y', 50)
  def _reduce_15(val, _values, result)
            handler.push_object(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 54)
  def _reduce_16(val, _values, result)
            position = scanner.current_position
        handler.push_empty_object(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 58)
  def _reduce_17(val, _values, result)
            handler.push_value(val[2])

    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'toon.y', 65)
  def _reduce_21(val, _values, result)
            handler.push_value(val[0], key: true)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 70)
  def _reduce_22(val, _values, result)
            handler.pop
        scanner.reset_delimiters

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 74)
  def _reduce_23(val, _values, result)
            handler.pop
        scanner.reset_delimiters

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 78)
  def _reduce_24(val, _values, result)
            handler.pop

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 81)
  def _reduce_25(val, _values, result)
            handler.pop
        scanner.reset_delimiters

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 85)
  def _reduce_26(val, _values, result)
            handler.pop
        scanner.reset_delimiters

    result
  end
.,.,

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'toon.y', 94)
  def _reduce_31(val, _values, result)
            scanner.delimiter(val[2])
        handler.push_array(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 99)
  def _reduce_32(val, _values, result)
            scanner.any_delimiters

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 107)
  def _reduce_33(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 107)
  def _reduce_34(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 107)
  def _reduce_35(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 103)
  def _reduce_36(val, _values, result)
            each_list_item(val) { |v, _| handler.push_value(v, tabular_field: true) }

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 111)
  def _reduce_37(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 111)
  def _reduce_38(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 111)
  def _reduce_39(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 107)
  def _reduce_40(val, _values, result)
            each_list_item(val) { |v, _| handler.push_value(v) }

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 113)
  def _reduce_41(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 113)
  def _reduce_42(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 113)
  def _reduce_43(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'toon.y', 113)
  def _reduce_45(val, _values, result)
            scanner.reset_delimiters

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 117)
  def _reduce_46(val, _values, result)
            position = scanner.current_position
        handler.push_empty_object(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 121)
  def _reduce_47(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'toon.y', 129)
  def _reduce_50(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 129)
  def _reduce_51(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 129)
  def _reduce_52(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'toon.y', 129)
  def _reduce_54(val, _values, result)
            each_list_item(val) do |v, i|
          handler.push_value(v, tabular_value: true, head_value: i.zero?)
        end

    result
  end
.,.,

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

module_eval(<<'.,.,', 'toon.y', 141)
  def _reduce_59(val, _values, result)
            result = Toonrb::Nodes::QuotedString.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 144)
  def _reduce_60(val, _values, result)
            result = Toonrb::Nodes::UnquotedString.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 148)
  def _reduce_61(val, _values, result)
            result = Toonrb::Nodes::Boolean.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 152)
  def _reduce_62(val, _values, result)
            result = Toonrb::Nodes::Null.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 156)
  def _reduce_63(val, _values, result)
            result = Toonrb::Nodes::Number.new(val[0])

    result
  end
.,.,

# reduce 64 omitted

# reduce 65 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
end   # module Toonrb
