# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "toon.y".
#

require 'racc/parser.rb'
module Toonrb
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    16,    23,    24,    25,    26,    27,    58,    23,    24,    25,
    26,    27,     4,    16,    16,     5,    28,    40,    36,    39,
    23,    24,    25,    26,    27,     4,    16,    16,     5,    23,
    24,    45,    16,    23,    24,    25,    26,    27,    48,    23,
    24,    25,    26,    27,    48,    16,    23,    24,    25,    26,
    27,    16,    23,    24,    25,    26,    27,    85,    23,    24,
    25,    26,    27,    85,    23,    24,    25,    26,    27,    23,
    24,   -50,    23,    24,    25,    26,    27,    23,    24,    25,
    26,    27,    23,    24,    23,    24,    23,    24,    30,    31,
   -65,    27,    41,    42,    43,    52,    63,    70,    72,    73,
    74,    75,    70,    79,    80,    83,    90,    91,    94,    70,
    70,    75,    99,    80,   102,    70,   106,    91,   109,   112,
   102,    70,    70,   117,    70 ]

racc_action_check = [
     0,    39,    39,    39,    39,    39,    39,     0,     0,     0,
     0,     0,     0,     2,    10,     0,     1,    17,    10,    17,
     2,     2,     2,     2,     2,     2,    36,    34,     2,     9,
     9,    34,    45,    36,    36,    36,    36,    36,    36,    45,
    45,    45,    45,    45,    45,    62,    42,    42,    42,    42,
    42,   102,    62,    62,    62,    62,    62,    62,   102,   102,
   102,   102,   102,   102,    64,    64,    64,    64,    64,    32,
    32,    64,    75,    75,    75,    75,    75,    91,    91,    91,
    91,    91,    40,    40,    80,    80,    94,    94,     3,     8,
    11,    15,    18,    19,    28,    38,    41,    48,    49,    53,
    54,    55,    58,    59,    60,    61,    65,    66,    71,    72,
    74,    76,    79,    81,    84,    85,    86,    92,    93,    99,
   103,   106,   109,   111,   112 ]

racc_action_pointer = [
    -2,    16,    11,    70,   nil,   nil,   nil,   nil,    75,    20,
    12,    76,   nil,   nil,   nil,    78,   nil,    13,    77,    78,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    94,   nil,
   nil,   nil,    60,   nil,    25,   nil,    24,   nil,    87,    -8,
    73,    89,    37,   nil,   nil,    30,   nil,   nil,    80,    84,
   nil,   nil,   nil,    96,    86,    93,   nil,   nil,    85,    98,
    96,    89,    43,   nil,    55,    90,    99,   nil,   nil,   nil,
   nil,    93,    92,   nil,    93,    63,   103,   nil,   nil,   106,
    75,   105,   nil,   nil,   107,    98,   102,   nil,   nil,   nil,
   nil,    68,   109,   104,    77,   nil,   nil,   nil,   nil,   105,
   nil,   nil,    49,   113,   nil,   nil,   104,   nil,   nil,   105,
   nil,   107,   107,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -75,    -1,   -75,    -4,    -5,    -6,    -7,   -75,    -9,
   -75,   -14,   -24,   -25,   -26,   -75,   -30,   -75,   -38,   -52,
   -66,   -67,   -68,   -69,   -70,   -72,   -73,   -74,   -75,    -2,
    -3,    -8,    -9,   -11,   -75,   -17,   -75,   -13,   -27,   -71,
   -75,   -75,   -71,   119,   -10,   -75,   -16,   -12,   -18,   -75,
   -22,   -65,   -28,   -75,   -75,   -33,   -36,   -37,   -18,   -75,
   -56,   -75,   -75,   -45,   -71,   -75,   -60,   -63,   -64,   -15,
   -19,   -20,   -18,   -29,   -18,   -71,   -33,   -35,   -40,   -75,
   -75,   -56,   -58,   -39,   -42,   -18,   -75,   -48,   -49,   -51,
   -53,   -71,   -60,   -75,   -75,   -21,   -31,   -32,   -34,   -75,
   -55,   -57,   -75,   -42,   -44,   -46,   -18,   -59,   -61,   -18,
   -14,   -75,   -18,   -41,   -43,   -47,   -62,   -23,   -54 ]

racc_goto_table = [
     8,    11,     8,    11,    33,    37,    71,    84,    93,   104,
    35,    47,    88,    55,    57,    65,    78,    77,     1,    38,
    69,    82,     3,    53,    29,    54,    61,    44,   114,    46,
    95,    50,    96,    35,   108,    62,    49,    89,    98,    56,
    50,    60,   101,   105,   111,    49,    59,   113,   107,    97,
    57,   nil,    88,   nil,   nil,   nil,   nil,    87,   nil,   nil,
   nil,   nil,    86,    11,   115,   nil,   nil,   116,   nil,   nil,
   118,   nil,   nil,   nil,   nil,    56,   nil,   nil,   nil,   nil,
   nil,   100,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   110,   nil,    87,   nil,   nil,
   nil,   nil,    86,    11 ]

racc_goto_check = [
     6,    12,     6,    12,     9,     5,    14,    30,    41,    32,
    12,    11,     4,    23,    26,    35,    14,    25,     1,    20,
    11,    38,     3,    21,     3,    22,    28,     9,    32,     5,
    14,     5,    14,    12,    41,    29,     6,    35,    25,     6,
     5,    12,    38,    14,     4,     6,    36,    30,    39,    23,
    26,   nil,     4,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,     6,    12,    14,   nil,   nil,    14,   nil,   nil,
    14,   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,
   nil,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    12,   nil,     5,   nil,   nil,
   nil,   nil,     6,    12 ]

racc_goto_pointer = [
   nil,    18,   nil,    22,   -50,    -5,     0,   nil,   nil,    -5,
   nil,   -25,     1,   nil,   -42,   nil,   nil,   nil,   nil,   nil,
     4,   -15,   -14,   -26,   nil,   -38,   -25,   nil,   -15,    -6,
   -55,   nil,   -75,   nil,   nil,   -27,     6,   nil,   -39,   -43,
   nil,   -58,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,   nil,     6,     7,    67,     9,    32,   nil,
    10,   nil,    51,    34,   nil,    12,    13,    14,    17,    15,
    22,   nil,   nil,   nil,    76,   nil,    68,    18,   nil,   nil,
   nil,   103,   nil,    19,    64,   nil,   nil,    81,   nil,    66,
    92,   nil,    20,    21 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 23, :_reduce_1,
  2, 23, :_reduce_2,
  2, 21, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  2, 22, :_reduce_8,
  0, 29, :_reduce_9,
  2, 29, :_reduce_10,
  2, 24, :_reduce_11,
  3, 27, :_reduce_none,
  2, 27, :_reduce_none,
  1, 30, :_reduce_14,
  3, 28, :_reduce_none,
  2, 28, :_reduce_none,
  1, 33, :_reduce_17,
  0, 34, :_reduce_none,
  1, 34, :_reduce_none,
  2, 31, :_reduce_20,
  3, 31, :_reduce_21,
  1, 31, :_reduce_none,
  5, 31, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  0, 41, :_reduce_none,
  1, 41, :_reduce_none,
  4, 38, :_reduce_29,
  1, 39, :_reduce_30,
  5, 35, :_reduce_31,
  2, 44, :_reduce_32,
  0, 45, :_reduce_33,
  2, 45, :_reduce_34,
  2, 42, :_reduce_35,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  1, 36, :_reduce_38,
  4, 36, :_reduce_39,
  4, 47, :_reduce_none,
  2, 51, :_reduce_41,
  0, 52, :_reduce_42,
  2, 52, :_reduce_43,
  3, 48, :_reduce_none,
  1, 49, :_reduce_45,
  2, 50, :_reduce_46,
  3, 50, :_reduce_47,
  1, 50, :_reduce_none,
  1, 50, :_reduce_none,
  1, 55, :_reduce_50,
  2, 55, :_reduce_51,
  1, 37, :_reduce_52,
  4, 37, :_reduce_53,
  7, 53, :_reduce_none,
  2, 57, :_reduce_55,
  0, 58, :_reduce_56,
  2, 58, :_reduce_57,
  2, 56, :_reduce_58,
  2, 60, :_reduce_59,
  0, 61, :_reduce_60,
  2, 61, :_reduce_61,
  4, 54, :_reduce_62,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 32, :_reduce_69,
  1, 32, :_reduce_70,
  0, 46, :_reduce_71,
  1, 62, :_reduce_72,
  1, 63, :_reduce_73,
  1, 40, :_reduce_74 ]

racc_reduce_n = 75

racc_shift_n = 119

racc_token_table = {
  false => 0,
  :error => 1,
  :L_BRACKET => 2,
  :R_BRACKET => 3,
  :L_BRACE => 4,
  :R_BRACE => 5,
  :COLON => 6,
  :HYPHEN => 7,
  :DELIMITER => 8,
  :QUOTED_STRING => 9,
  :UNQUOTED_STRING => 10,
  :BOOLEAN => 11,
  :NULL => 12,
  :NUMBER => 13,
  :NL => 14,
  :PUSH_INDENT => 15,
  :POP_INDENT => 16,
  :BLANK => 17,
  :EOS => 18,
  "-temp-group" => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "L_BRACKET",
  "R_BRACKET",
  "L_BRACE",
  "R_BRACE",
  "COLON",
  "HYPHEN",
  "DELIMITER",
  "QUOTED_STRING",
  "UNQUOTED_STRING",
  "BOOLEAN",
  "NULL",
  "NUMBER",
  "NL",
  "PUSH_INDENT",
  "POP_INDENT",
  "BLANK",
  "EOS",
  "\"-temp-group\"",
  "$start",
  "root",
  "root_item",
  "\"-many@root_item\"",
  "object",
  "array",
  "primitive",
  "object_head_item",
  "object_item",
  "\"-many@object_item\"",
  "object_head_key",
  "object_value",
  "string",
  "object_key",
  "\"-option@BLANK\"",
  "inline_array",
  "list_array",
  "tebular_array",
  "array_header_common",
  "array_header_start",
  "number",
  "\"-option@DELIMITER\"",
  "inline_array_values",
  "inline_array_value",
  "\"-group@DELIMITER-inline_array_value\"",
  "\"-many@-group@DELIMITER-inline_array_value\"",
  "empty_string",
  "list_array_header",
  "list_array_items",
  "list_array_start",
  "list_array_value",
  "\"-group@HYPHEN-list_array_value\"",
  "\"-many@-group@HYPHEN-list_array_value\"",
  "tebular_array_header",
  "tabular_row",
  "\"-many1@tabular_row\"",
  "tabular_fields",
  "\"-group@DELIMITER-string\"",
  "\"-many@-group@DELIMITER-string\"",
  "tabular_row_value",
  "\"-group@DELIMITER-tabular_row_value\"",
  "\"-many@-group@DELIMITER-tabular_row_value\"",
  "boolean",
  "null" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_1(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'toon.y', 29)
  def _reduce_8(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 38)
  def _reduce_9(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 38)
  def _reduce_10(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 34)
  def _reduce_11(val, _values, result)
            handler.pop

    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'toon.y', 41)
  def _reduce_14(val, _values, result)
            handler.push_object(val[0])

    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'toon.y', 48)
  def _reduce_17(val, _values, result)
            handler.push_value(val[0], key: true)

    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'toon.y', 52)
  def _reduce_20(val, _values, result)
            position = scanner.current_position
        handler.push_empty_object(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 56)
  def _reduce_21(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'toon.y', 67)
  def _reduce_29(val, _values, result)
            scanner.delimiter(val[2])
        handler.push_array(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 72)
  def _reduce_30(val, _values, result)
            scanner.start_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 76)
  def _reduce_31(val, _values, result)
            handler.pop
        scanner.end_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 85)
  def _reduce_32(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 85)
  def _reduce_33(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 85)
  def _reduce_34(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 81)
  def _reduce_35(val, _values, result)
            each_list_item(val) { |v, _| handler.push_value(v) }

    result
  end
.,.,

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'toon.y', 88)
  def _reduce_38(val, _values, result)
            handler.pop
        scanner.end_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 92)
  def _reduce_39(val, _values, result)
            handler.pop
        scanner.end_list_array_items
        scanner.end_array

    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'toon.y', 102)
  def _reduce_41(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 102)
  def _reduce_42(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 102)
  def _reduce_43(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'toon.y', 102)
  def _reduce_45(val, _values, result)
            scanner.start_list_array_items

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 106)
  def _reduce_46(val, _values, result)
            handler.push_empty_object(val[0])
        handler.push_blank(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 110)
  def _reduce_47(val, _values, result)
            handler.push_value(val[0])
        handler.push_blank(val[2])

    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'toon.y', 126)
  def _reduce_50(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 126)
  def _reduce_51(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 117)
  def _reduce_52(val, _values, result)
            handler.pop
        scanner.end_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 121)
  def _reduce_53(val, _values, result)
            handler.pop
        scanner.end_array

    result
  end
.,.,

# reduce 54 omitted

module_eval(<<'.,.,', 'toon.y', 132)
  def _reduce_55(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 132)
  def _reduce_56(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 132)
  def _reduce_57(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 128)
  def _reduce_58(val, _values, result)
            each_list_item(val) { |v, _| handler.push_value(v, tabular_field: true) }

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 139)
  def _reduce_59(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 139)
  def _reduce_60(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 139)
  def _reduce_61(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 132)
  def _reduce_62(val, _values, result)
            each_list_item(val) do |v, i|
          handler.push_value(v, tabular_value: true, head_value: i.zero?)
        end
        handler.push_blank(val[3], tabular_value: true, head_value: true)

    result
  end
.,.,

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'toon.y', 148)
  def _reduce_69(val, _values, result)
            result = handler.quoted_string(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 151)
  def _reduce_70(val, _values, result)
            result = handler.unquoted_string(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 155)
  def _reduce_71(val, _values, result)
            position = scanner.current_position
        result = handler.empty_string(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 160)
  def _reduce_72(val, _values, result)
            result = handler.boolean(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 164)
  def _reduce_73(val, _values, result)
            result = handler.null(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 168)
  def _reduce_74(val, _values, result)
            result = handler.number(val[0])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
end   # module Toonrb
